// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ReabastecimientoPanaderia.DB.Data;

#nullable disable

namespace ReabastecimientoPanaderia.DB.Migrations
{
    [DbContext(typeof(Context))]
    [Migration("20260410025454_RenglonAndGeneralConfigs")]
    partial class RenglonAndGeneralConfigs
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ReabastecimientoPanaderia.DB.Data.Entities.Pedido", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<DateTime>("FechaYHora")
                        .HasColumnType("datetime2");

                    b.HasKey("ID");

                    b.HasIndex("FechaYHora");

                    b.ToTable("Pedidos");
                });

            modelBuilder.Entity("ReabastecimientoPanaderia.DB.Data.Entities.Producto", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<bool>("EsComun")
                        .HasColumnType("bit");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("TipoProductoID")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("Nombre")
                        .IsUnique();

                    b.HasIndex("TipoProductoID", "Nombre")
                        .IsUnique();

                    b.ToTable("Productos");
                });

            modelBuilder.Entity("ReabastecimientoPanaderia.DB.Data.Entities.Renglon", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<int>("CantidadSolicitada")
                        .HasColumnType("int");

                    b.Property<string>("NombreProducto")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PedidoID")
                        .HasColumnType("int");

                    b.Property<int?>("ProductoSolicitadoID")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("ProductoSolicitadoID");

                    b.HasIndex("PedidoID", "ProductoSolicitadoID")
                        .IsUnique()
                        .HasFilter("[ProductoSolicitadoID] IS NOT NULL");

                    b.ToTable("Renglones");
                });

            modelBuilder.Entity("ReabastecimientoPanaderia.DB.Data.Entities.TipoProducto", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("nvarchar(3)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("ID");

                    b.HasIndex("Codigo")
                        .IsUnique();

                    b.HasIndex("Nombre")
                        .IsUnique();

                    b.ToTable("TiposProducto");
                });

            modelBuilder.Entity("ReabastecimientoPanaderia.DB.Data.Entities.Producto", b =>
                {
                    b.HasOne("ReabastecimientoPanaderia.DB.Data.Entities.TipoProducto", "TipoProducto")
                        .WithMany("Productos")
                        .HasForeignKey("TipoProductoID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("TipoProducto");
                });

            modelBuilder.Entity("ReabastecimientoPanaderia.DB.Data.Entities.Renglon", b =>
                {
                    b.HasOne("ReabastecimientoPanaderia.DB.Data.Entities.Pedido", "Pedido")
                        .WithMany("Renglones")
                        .HasForeignKey("PedidoID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ReabastecimientoPanaderia.DB.Data.Entities.Producto", "ProductoSolicitado")
                        .WithMany()
                        .HasForeignKey("ProductoSolicitadoID")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Pedido");

                    b.Navigation("ProductoSolicitado");
                });

            modelBuilder.Entity("ReabastecimientoPanaderia.DB.Data.Entities.Pedido", b =>
                {
                    b.Navigation("Renglones");
                });

            modelBuilder.Entity("ReabastecimientoPanaderia.DB.Data.Entities.TipoProducto", b =>
                {
                    b.Navigation("Productos");
                });
#pragma warning restore 612, 618
        }
    }
}
